### ISSUE TITLE
Input not listening for programatically changed values

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#11]
Something like

    <Input value={this.state.test}/>
    <button onClick={()=>this.setState({test:'Test'})}>Click</button>

Will not update the presented value in the input. (The code is valid for a native `<input/>`.)

This is of course just a quick gist, it does not matter if the data is incoming from the props.

**Comment by GU5TAF** [comment]
This should also have been fixed in https://github.com/nordnet/nordnet-ui-kit/commit/b0c4e27f5a8b26558344ffb22408d313df70c2db by [this](https://github.com/nordnet/nordnet-ui-kit/commit/b0c4e27f5a8b26558344ffb22408d313df70c2db#diff-4e647f77b7721f331a3cf38b536d622eR45) line.

**Comment by JohnPhoto** [comment]
The fix works for me.
