### ISSUE TITLE
Input[type=number] not looking good with hasError

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#12]
![screen shot 2016-02-05 at 12 30 29](https://cloud.githubusercontent.com/assets/3659871/12845163/690dada6-cc04-11e5-81e8-f0130425d71c.png)

The ! is not looking so good when hasError is true and the input type is number with the native up/down-buttons. 

Chrome btw.

**Comment by GU5TAF** [comment]
<img width="245" alt="better error handling number input" src="https://cloud.githubusercontent.com/assets/3854323/13352073/2a772c4c-dc8b-11e5-8cbc-de797afb6d9c.png">

This should be fixed by https://github.com/nordnet/nordnet-ui-kit/commit/8811ae6642fd1fb87ef5a7a2de1e5b2161bc91a5

**Comment by JohnPhoto** [comment]
Works good now.
