### ISSUE TITLE
Button breaking native api

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#13]
Native buttons have type = [button, reset, submit]. I need to be able to set this in my forms.
Please consider changing the current type = [danger, warning, etc]

**Comment by GU5TAF** [comment]
woops, I'll have to rethink what we're gonna call the [success, warning, danger] modifiers.


maybe:
```
<Button primary modifier="success">Click</Button>
```

or

```
<Button primary success>Click</Button>
```

thoughts?

**Comment by JohnPhoto** [comment]
`<Button primary modifier="success">Click</Button>`

Likie, easier for fancy stuff like: 

`<Button primary modifier={this.props.modifier}>Click</Button>`

(examplecode, could ofcourse be prettified.)

**Comment by GU5TAF** [comment]
Right, of course!
I'll do the same with the alert component as I want a common behaviour for this across the board apart from validation of input elements. I'll keeps those as `hasSuccess` etc.
Sound good?

**Comment by JohnPhoto** [comment]
Sounds good yes.

**Comment by iamstarkov** [comment]
I came here from #26. If `type` prop will be changed to `theme` then there will be no problems

**Comment by GU5TAF** [comment]
@iamstarkov why would it be better to name the prop 'theme' instead of modifier?
