### ISSUE TITLE
Input type=submit

### ISSUE THREAD

**Issue by lalala** [nordnet/nordnet-ui-kit#16]
Doesn't exist :-(

And using a button is not a substitute.

**Comment by JohnPhoto** [comment]
+1

**Comment by hassellof** [comment]
Quick workaround: Just add an invisible input type submit and use a button with onClick submit.

**Comment by bstream** [comment]
Currently we have support for `<Input type="submit" />` (technically, it does neither look or work great) and we also have support for `<Button type="submit" />`. I will close this for now, please open a new issue with more information regarding looks and use case if this is still an issue :)
