### ISSUE TITLE
Collapsible: Content with margin-top gets pushed down below the visible area

### ISSUE THREAD

**Issue by stigdanielek** [nordnet/nordnet-ui-kit#18]
If I give the Collapsible a DIV whose first child has a margin-top set, the DIV will be pushed down and the lower part will end up below the bottom edge of the visible area. However, if I apply the following CSS rule:

```
.collapsible__body > div {
  border: 1px solid rgba(0, 0, 0, 0);
}
```

things will render fine. There might of course be a more elegant solution/hack for this issue, but this invisible border does the trick for me at least.

**Comment by GU5TAF** [comment]
Could you give [react-collapse](https://github.com/nkbt/react-collapse) a go instead @stigdanielek?
I think I'm going to deprecate the built in collapse in favour of this one.

**Comment by stigdanielek** [comment]
OK.

**Comment by GU5TAF** [comment]
Assuming that (react-collapse)[https://github.com/nkbt/react-collapse] works well so I'm closing this issue.
Feel free to re-open if need be.

**Comment by stigdanielek** [comment]
Sorry, I forgot about this. Yes, react-collapse works fine for me. Thanks!
