### ISSUE TITLE
Flag: Option to get rectangular icon and fix for all browsers

### ISSUE THREAD

**Issue by bstream** [nordnet/nordnet-ui-kit#180]
* Add possibility to get rectangular or rounded flags
* Find a solution to make the rounded flags work in all browsers (currently they use clip-path, which is not well supported)

**Comment by JCB-K** [comment]
- allow capitalized language code

**Comment by bstream** [comment]
Fixed in 7af8669de788c97b5d2936b0e78d7347fb99ac80 and 4de15c8b4513267a71bfe53d861e828f27a80743
