### ISSUE TITLE
Difficult to identify disabled input

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#19]
Visually it is hard to tell that a disabled input is actually disabled. Might give frustration to users.

**Comment by GU5TAF** [comment]
<img width="100%" alt="disabled styles" src="https://cloud.githubusercontent.com/assets/3854323/13351828/b6225dae-dc89-11e5-8c4f-51d9cd75a71c.png">

Nice catch, committing proper disabled styles shortly :wink:
