### ISSUE TITLE
New variant of alert for the order placement error state

### ISSUE THREAD

**Issue by geordidearns** [nordnet/nordnet-ui-kit#198]
If an order gets rejected or errors, it needs a error styled like this 
![screen shot 2017-05-05 at 10 48 12](https://cloud.githubusercontent.com/assets/5615153/25739090/9d5f8768-3180-11e7-9edb-aabe3eb374d7.png)

We spoke about keeping the existing one as the primary, and adding this style as a prop

**Comment by willeeklund** [comment]
This will be solved by #206.
