### ISSUE TITLE
(Discussion) Awkward syntax on Input

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#2]
The <Input> element get kind of bloaty that you have to define both label and placeholder if one would always like to show "First Name".

**Comment by JohnPhoto** [comment]
Suggestion would be: Default with the same as the other if no explicit is defined.

**Comment by GU5TAF** [comment]
Fixed this in e2ec0fa so that if no placeholder prop is specified it'll use the label instead, will publish a new version later today :wink:
