### ISSUE TITLE
Select Input styling errors

### ISSUE THREAD

**Issue by geordidearns** [nordnet/nordnet-ui-kit#210]
Hi, theres a few styling issues with the UI kit select, I will pot images below and try to explain. Let me know if you need me to show you in person :)

1) The placeholder is not aligned in the center, there seems to be a hard-coded top:4px on it, if set to 0 it looks fine.
![screen shot 2017-05-11 at 14 02 09](https://cloud.githubusercontent.com/assets/5615153/25948186/b8c5b186-3652-11e7-86ee-009aa5fa0d57.png)

2) When i select an option - the placeholder doesn't disappear
![screen shot 2017-05-11 at 14 02 17](https://cloud.githubusercontent.com/assets/5615153/25948221/d4fa52f8-3652-11e7-853f-85434aae72c5.png)

3) Names with long tails 'p' for example, gets trimmed from the name. There is an explicit height 1.2rem on it which looks to be causing it
![screen shot 2017-05-11 at 14 03 05](https://cloud.githubusercontent.com/assets/5615153/25948271/0c4687ae-3653-11e7-8210-9b62576540ed.png)

4) The arrow is hardcoded but off aligned, the bottom:10px seems to be doing it.
![screen shot 2017-05-11 at 14 03 14](https://cloud.githubusercontent.com/assets/5615153/25948295/211b43cc-3653-11e7-8dcb-a225e1b7a1f6.png)

Comment if you need more clarification. Thanks

**Comment by geordidearns** [comment]
@willeeklund @bstream - I can't assign people on github

**Comment by willeeklund** [comment]
Thanks for the report @geordidearns . I will look into it!
