### ISSUE TITLE
Fix styling on select input

### ISSUE THREAD

**Issue by geordidearns** [nordnet/nordnet-ui-kit#219]
Hi,

Just a few styling issues on the select input: will attach images and explain.
![screen shot 2017-05-15 at 17 00 06](https://cloud.githubusercontent.com/assets/5615153/26064006/f9bbdae0-398f-11e7-86de-62405d46f552.png)

This happens with long names, here is the fix for it:
![screen shot 2017-05-15 at 16 55 52](https://cloud.githubusercontent.com/assets/5615153/26064045/1569a894-3990-11e7-9ad7-c065499a175d.png)

also removing the 'pxm' on the padding-right on this, as it's invalid 
![screen shot 2017-05-15 at 17 01 38](https://cloud.githubusercontent.com/assets/5615153/26064086/373cc83e-3990-11e7-9285-a465b2fa9f73.png)

Thanks :)

**Comment by geordidearns** [comment]
Tagging for reference @bstream @willeeklund

**Comment by geordidearns** [comment]
Also, it would be awesome to support this attribute: https://www.w3schools.com/tags/att_global_title.asp

Which would allow the long truncated names to be shown in full on hover. Please ask any questions if you have any

**Comment by JCB-K** [comment]
@geordidearns `text-overflow: ellipsis` would in this case hide the account number. Is that acceptable behaviour?

For reference, `pxm` typo is here: https://github.com/nordnet/nordnet-ui-kit/blame/master/src/components/input/input-select-styles.jsx#L23

**Comment by iamstarkov** [comment]
`text-overflow` is a nice suggestion

**Comment by iamstarkov** [comment]
i would say we go with `white-space: nowrap`, `text-overflow: ellipsis` and a bit `padding-right` magic
![screen shot 2017-05-15 at 9 41 57 pm](https://cloud.githubusercontent.com/assets/559321/26075927/57814486-39b7-11e7-8bc4-e1620bb552bf.png)
