### ISSUE TITLE
Erasing after focus is dodgy

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#23]
Given: Input has a value and is blurred.
When: Focus to input (visually is all the text selected), press backspace to remove text.
Then: Deselect text, no actual change of text.

**Comment by GU5TAF** [comment]
@JohnPhoto I'm go go ahead and close this issue as it's fixed, feel free to reopen it if it isn't fixed.

**Comment by JohnPhoto** [comment]
The fix works for me aswell.
