### ISSUE TITLE
Nordnet style for react-date-picker

### ISSUE THREAD

**Issue by NN-Tobbe** [nordnet/nordnet-ui-kit#24]
I would like a nordnet looking css for the zippy-ui react-date-picker https://github.com/zippyui/react-date-picker

**Comment by GU5TAF** [comment]
<img width="401" alt="screenshot 2016-03-29 17 50 23" src="https://cloud.githubusercontent.com/assets/3854323/14114310/c5f48994-f5d6-11e5-97c1-43e1883fc013.png">

Not yet complete but getting there, will publish a new version once it's done.

**Comment by GU5TAF** [comment]
react-date-picker theme is now in the latest version 💥
