### ISSUE TITLE
button variable type support

### ISSUE THREAD

**Issue by iamstarkov** [nordnet/nordnet-ui-kit#26]
```jsx
import { Button } from 'nordnet-ui-kit';
const randomBoolean = () => Boolean(Math.round(Math.random()));

import 'nordnet-ui-kit/dist/button/button.css';

class Example extends React.Component {
  render() {
    return (<div>
      <div>Current implementation
        randomBoolean()
          ? <Button primary> text </Button>
          : <Button seconday> text </Button>
      </div>
      <div>Proposed implementation
        <Button type={randomBoolean() ? 'primary' : 'seconday'}> text </Button>
      </div>
    </div>)
  }
}
```

Proposed solution seems to be a bit simpler. what do you think?

**Comment by GU5TAF** [comment]
That's how it was originally, see #13 for the discussion as to why it was changed.

**Comment by GU5TAF** [comment]
Sorry, I read this poorly.
You're talking about primary and secondary not danger, success, warning etc.
I do see the use case for this, reopening!

**Comment by GU5TAF** [comment]
Regarding the actual property's name, we could perhaps call it `variant`.
that way we'd have `variant` and `modifier` which both feel generic and flexible enough to cover most use cases.
Thoughts?

**Comment by iamstarkov** [comment]
i would like to check few design kit conventions before, we'll be back tomorrow

**Comment by iamstarkov** [comment]
`variant` is good
