### ISSUE TITLE
Select input not expanding in Firefox [55.0.3]

### ISSUE THREAD

**Issue by KitsuneKelso** [nordnet/nordnet-ui-kit#275]
Clicking on the [Input type="select"](https://nordnet.github.io/nordnet-ui-kit/#input) in Firefox doesn't work as intended:

- The select gets focus,
- The drop-down appears for a fraction of a second, but closes,

A second click is required, when the select already has focus, in order to get the drop-down to remain opened.

(I tried to capture a video of it, but github only accepted gif's, sorry for the quality)

![input](https://user-images.githubusercontent.com/13475700/30365423-0065c3c4-9868-11e7-9d71-ab5ddab3fdcd.gif)

**Comment by bstream** [comment]
Thanks for your detailed report! Will try to find time to investigate why this happens!
