### ISSUE TITLE
Input type Radio and Checkbox missing focus on Safari

### ISSUE THREAD

**Issue by KitsuneKelso** [nordnet/nordnet-ui-kit#298]
The focus indicator does not display in Safari for Radio-buttons and Check-boxes.

Here's what it looks like in Chrome:
![screen shot 2017-10-19 at 13 33 21](https://user-images.githubusercontent.com/13475700/31769035-2f1b8fce-b4d2-11e7-8196-4829f0618bbf.png)
![screen shot 2017-10-19 at 13 33 33](https://user-images.githubusercontent.com/13475700/31769036-31360b18-b4d2-11e7-8f97-17f6eb217d18.png)

And in Safari:
![screen shot 2017-10-19 at 13 33 48](https://user-images.githubusercontent.com/13475700/31769044-36b547b6-b4d2-11e7-9507-480b796492ef.png)
![screen shot 2017-10-19 at 13 33 53](https://user-images.githubusercontent.com/13475700/31769046-388f3632-b4d2-11e7-8f24-ef98fe26b14d.png)

**Comment by bstream** [comment]
See this comment (the issue is similar, clicking does not trigger focus - tabbing does): https://github.com/nordnet/nordnet-ui-kit/issues/299#issuecomment-338155556
