### ISSUE TITLE
make it easy to use px instead of rem

### ISSUE THREAD

**Issue by GU5TAF** [nordnet/nordnet-ui-kit#31]
To make the UI kit work on the current Nordnet site we can't use rems but on anything new we should.
I added a flag to variables as well as a mixin that makes toggling between rem and px easy.

Needs to be applied everywhere, see [here](https://github.com/nordnet/nordnet-ui-kit/commit/a49ce174efa72962f61fe1c45c65793d964b4f98#diff-c8a15b86257d0e726fdaf55d4aa14c4aR46) for how it's done.

**Comment by iamstarkov** [comment]
For internal use cases that's fine, but if external consumer will be asked to build sass templates if they don't use rem, then it can be a problem

**Comment by GU5TAF** [comment]
Why wouldn't the proposed solution work for external consumers?
```scss
$use-rem: false;
@import '~nordnet-ui-kit/src/button/button';
```

I'd need to add an index.scss file that would allow doing it on the bundle as well though.

**Comment by GU5TAF** [comment]
We could of course also prebuild px versions and include them in the dist folder, should be pretty easy using [sass-loader environment variables](https://github.com/jtangelder/sass-loader#environment-variables).

**Comment by iamstarkov** [comment]
> Why wouldn't the proposed solution work for external consumers?

if they are not using sass themself, then they would need to add `node-sass` to their deps and wait for it to install and to process their css every time they change smth.

> I'd need to add an index.scss file that would allow doing it on the bundle as well though.

that would be the best solution

**Comment by GU5TAF** [comment]
That's a valid point, if they want to make any other changes to the UI kit they'd have to do that anyway but I get where you're coming from. Adding an index.scss file would also require that.

Do you prefer the idea of including prebuilt px versions @iamstarkov? That's what I'm leaning towards right now.

**Comment by iamstarkov** [comment]
prebuilt versions is fine.

bootstrap is also provide basic css build for simple usage and sass files for advanced one

**Comment by GU5TAF** [comment]
take a look at https://github.com/nordnet/nordnet-ui-kit/commit/d4024708bbd22b66a0d41a4f42f43c6b9b474db6 @iamstarkov, now it'll build a px version of every entrypoint. What do you think?

**Comment by iamstarkov** [comment]
seems like a good solution

**Comment by iamstarkov** [comment]
is it published already?

**Comment by GU5TAF** [comment]
yes it is
