### ISSUE TITLE
Prevent tooltip from going off the screen on mobile

### ISSUE THREAD

**Issue by mlenser** [nordnet/nordnet-ui-kit#339]
Similar to #327 the tooltip goes off the page a bit, but on mobile. This only occurs on a tooltip places slightly right of center. Another tooltip placed dead center does not have this issue.

It's pre-rendered so it creates a bit of a horizontal scroll bar even when not hovered (I've scrolled over, the darker gray is normally not so visible).

The tooltip is using a fixed width of 300 and the mobile size is 320.

![screen shot 2018-01-16 at 15 00 26](https://user-images.githubusercontent.com/235857/34992611-03db2e18-face-11e7-8bf9-505eef324366.png)

**Comment by jesperwiner** [comment]
Tooltip placement need a big overhaul. We need it smarter so it can decide itself better where to render. 

In next we have a lot of issues with it being rendered offscreen especially if you decrease screen size
