### ISSUE TITLE
Pls add Steps Progress

### ISSUE THREAD

**Issue by There5a** [nordnet/nordnet-ui-kit#35]
Vertical example:
![image](https://cloud.githubusercontent.com/assets/18049377/14017391/60427114-f1c7-11e5-9e04-cedbd6024097.png)

**Comment by iamstarkov** [comment]
can you attach Sketch UI Kit here?

**Comment by KitsuneKelso** [comment]
I am currently working on this as part of the onboarding page, I can probably make a pull request to add it as part of the ui-kit when it's done. :)

**Comment by GU5TAF** [comment]
That'd be great @KitsuneKelso

**Comment by bstream** [comment]
Please open a new issue if this is still needed
