### ISSUE TITLE
Subsection SSR and resize issues

### ISSUE THREAD

**Issue by bstream** [nordnet/nordnet-ui-kit#374]
* SSR - `onDesktop` (https://github.com/nordnet/nordnet-ui-kit/blob/master/src/components/subsection/subsection.jsx#L20) is reliying on `window` for proper execution (https://github.com/nordnet/nordnet-ui-kit/blob/master/src/components/subsection/subsection.jsx#L99), which will not work on the server and lead to inconsistencies in SSR -> Mobile + SSR -> Desktop
* Resize issues - There is no resize listener so if the window is resized after initial render the component will not re-render. However, if something else triggers a re-render it will now change according to screen size

**Comment by gish** [comment]
This was considered, although not communicated, during the implementation of the widget. Since it's mobile first, it was assumed it would be OK to have mobile version of the subsection in the SSR-version of the page.

Not my greatest achievement. I can admit that.
