### ISSUE TITLE
Add colors to the documentation

### ISSUE THREAD

**Issue by Arclights** [nordnet/nordnet-ui-kit#380]
It would be nice to have the colors available listed in the documentation in some way so you don't have to find it through the code/github.

**Comment by bstream** [comment]
Agreed! I linked this issue from an older one that had this as a subtask. Also, @JCB-K showed me a crude version of documenting colors the other day. Will check if I/we can refine that :)

**Comment by Arclights** [comment]
Cool, didn't see that one 😄

**Comment by JCB-K** [comment]
@bstream @Arclights See pull request above. As you mentioned it's a bit crude, but good enough to use IMO.
