### ISSUE TITLE
unnecessary curly brackets for string props in documentation

### ISSUE THREAD

**Issue by JacobBlomgren** [nordnet/nordnet-ui-kit#389]
Maybe it's too trivial to even bother, but the documentation for the Tooltip component wraps string props in curly brackets unnecessarily, e.g. `placement={'left'}` it should be `placement="left"`. Feel free to ignore it if it's too trivial.

**Comment by mlenser** [comment]
👍

**Comment by bstream** [comment]
Maybe we could automate it with:
* https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md
* https://github.com/eslint/eslint-plugin-markdown

:)

**Comment by iamstarkov** [comment]
@JacobBlomgren care to share why it can be closed now?
