### ISSUE TITLE
Translatable Labels etc

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#4]
It would be nice if we don't have to pass around hardcoded strings to Input's and other elements. We want Intl and translation elements!

**Comment by dimchez** [comment]
That's a good point. It's tempting to have only dumb components in the UI kit. Maybe we could have an i18n version of each component that will handle translations. Any suggestions?

**Comment by JohnPhoto** [comment]
Yeah, maybe I was a bit rash in my demands. It might very well be enough for us to just pass in `<input label={this.props.getIntlMessage('X')}/>`

**Comment by JohnPhoto** [comment]
I ended up using the way in my previous comment.
