### ISSUE TITLE
Autocomplete bug

### ISSUE THREAD

**Issue by lagom3921** [nordnet/nordnet-ui-kit#45]
When autocomplete is active the placeholder text is overlapping. 

![screen shot 2016-04-28 at 16 02 23](https://cloud.githubusercontent.com/assets/1687533/14888603/65f8a4fc-0d5b-11e6-86bf-699ad999acc6.png)

**Comment by willeeklund** [comment]
I do not think this is the case anymore. Can not reproduce it. What do you say @bstream ? Time to close it?

**Comment by bstream** [comment]
Good find @willeeklund, yeah lets close it :)
