### ISSUE TITLE
Checkbox </3 redux-form

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#5]
The `<Checkbox/>` does not currently work with Redux-Form, I think the problem is the custom onChangeHandler in checkbox somehow. Will look into it and define what I'm exactly missing.

**Comment by JohnPhoto** [comment]
This is the object I get from redux-form which will autowire stuff if it is `spread` to the actual `<input/>`

	{
		active: false
		defaultChecked: false
		defaultValue: undefined
		dirty: false
		error: "Required"
		initialValue: undefined
		invalid: true
		name: "person.politicalPerson"
		onBlur: function(event)
		onChange: function(event)
		onDragStart: function(event)
		onDrop: function(event)
		onFocus: function ()
		onUpdate: function(event)
		pristine: true
		touched: false
		valid: false
		visited: false
	}

Normal `<Input>` works flawless with the following code, where `name` is the same structure as object above:

    <Input type="text" label="name" { ...name }/>

**Comment by JohnPhoto** [comment]
I have verified my suspicion, if I remove the "custom" `onChange` from the UIKit, the redux-logic works fine.

**Comment by GU5TAF** [comment]
I think https://github.com/nordnet/nordnet-ui-kit/commit/569dfc76eae9016de7f2480479c63bef18d9a3a0 solves this.

**Comment by GU5TAF** [comment]
could you perhaps confirm @JohnPhoto ?

**Comment by JohnPhoto** [comment]
I think this works now, will reopen if not so.
