### ISSUE TITLE
Radio not accepting bool.

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#6]
I have a boolean switch with radiobuttons (this is a legal thing, I would have prefered a checkbox, but I am not allowed that):

    <Radio value={true}/>
    <Radio value={false}/>

This gives the following warning:

> Warning: Failed propType: Invalid prop `value` of type `boolean` supplied to `Radio`, expected `string`. Check the render method of `PersonForm`.

Am I supposed to do another way, or is the use case bypassed?

**Comment by dimchez** [comment]
It looks like a bug to me.

**Comment by JohnPhoto** [comment]
Seems to be fixed now.
