### ISSUE TITLE
Input[type=number] not accepting numbers

### ISSUE THREAD

**Issue by JohnPhoto** [nordnet/nordnet-ui-kit#9]
Similiar problem as #6 but with normal inputs with HTML5 type number.

    <Input type="number" value={1}/>

> Warning: Failed propType: Invalid prop `value` of type `number` supplied to `Input`, expected `string`. Check the render method of `ValidatedInput`.

**Comment by GU5TAF** [comment]
Proptype should be fixed by https://github.com/nordnet/nordnet-ui-kit/commit/000be4e6ffc6e1381815e63830db0aff063b477b and handling of zeros as the value should be fixed by https://github.com/nordnet/nordnet-ui-kit/commit/8811ae6642fd1fb87ef5a7a2de1e5b2161bc91a5

**Comment by JohnPhoto** [comment]
Seems to work now.
